export const generalNamesInSelectedLanguage = {
  search: '',
  deleteButtonInfo: '',
  updateButtonInfo: '',
  seeDrawing: '',
  seeHistory: '',
  operationAddSuccessStatusMessage: '',
  operationAddFailerStatusMessage: '',
  operationUpdateSuccessStatusMessage: '',
  operationUpdateFailerStatusMessage: '',
  operationDeleteSuccessStatusMessage: '',
  operationDeleteFailerStatusMessage: '',
  name: '',
  code: '',
  select: '',
  closeButtonDescription: '',
  thisFieldIsRequired: '',
  saveButtonDescription: '',
  addNewButtonDescription: '',
  quantity: '',
  addNamesInAllLanguages: '',
  selectDrawingToUpload: 'Wybierz rysunke do udostępnienia',
  selectingDrawingIsRequired: 'Wybranie rysunku jest wymagane',
  upload: 'Udostępnij',
  uploadingDrawingIsRequired: 'Udostępnienie rysunku jest wymagane',
  drawingAddedSuccessStatus: 'Dodano rysunek',
  drawingAddedFailerStatus: 'Wystąpił błąd nie udało się dodać rysunku',
  onlyPngFormatIsAllowed: 'tylko format .png jest dozwolony',
  wrongEmailOrPassword: 'Nieprawidłowy email lub hasło',
  yourAccountIsInactive: 'Nie możesz się zalogować, Twoje konto jest nieaktywne, skontaktuj się z administratorem',
  loginFailerStatus: 'Wystąpił błąd, logowanie niepomyślne',
  chooseLanguageVersion: 'Wybierz wersję językową, klikająć na flagę',
  logInButtonDescription: 'Zaloguj się',
  thisCodeIstaken: 'Ten kod jest już zajęty',
  thisNameIsTaken: 'Podana nazwa jest już zajęta',
  codeMustContain2Characters: 'Kod musi zawierać 2 znaki',


};

export const generalUserNames = {
  partnerCode: '',
  partnerCompanyName: '',
  addNewBusinessPartner: '',
  addNewUser: '',
  fullName: '',
  email: '',
  changePassword: '',
  blockUser: '',
  unblockUser: '',
  businessPartnerOrders: '',
  userStatusBlocked: '',
  userStatusActive: '',
  userHasBennBlockedMessage: '',
  userHasBeenUnblockedMessage: '',
  admins: '',
  editors: '',
  userAddSuccessStatusMessage: '',
  userAddFailerStatusMessage: '',
  userUpdateSuccessStatusMessage: '',
  userUpdateFailerStatusMessage: '',
  userDeleteSuccessStatusMessage: '',
  userDeleteFailerStatusMessage: '',
  partnerAddSuccessStatusMessage: '',
  partnerAddFailerStatusMessage: '',
  partnerUpdateSuccessStatusMessage: '',
  partnerUpdateFailerStatusMessage: '',
  partnerDeleteSuccessStatusMessage: '',
  partnerDeleteFailerStatusMessage: '',
  updateBusinessPartner: '',
  updateUser: '',
  emailIsAlreadyTaken: '',
  emailMustBeValid: '',
  passwordIsRequired: '',
  passwordMustContain8Characters: '',
  passwordMustContain1CapitalLetter: '',
  passwordMustContain2Digest: '',
  passwordMustContain1smallLetter: '',
  noMatchBetweenPasswords: '',
  repeatPassword: '',
  repeatingPasswordIsRequired: '',
  password: '',
  active: '',
  passwordChangeSuccessStatus: '',
  passwordChangeFailerStatus: '',
  admin: '',
  editor: '',
  status: '',
  changeYourPassword: 'Zmień swoje hasło',
  currentPassword: '',
  newPassword: '',
};

export const orderNames = {
  orderNumber: '',
  businessPartner: '',
  creator: '',
  index: '',
  date: '',
  createNewOrder: '',
  submitButtonNext: '',
  ChangeMaterialButtonInfo: '',
  ConfirmMaterial: '',
  ChangePartner: '',
  ConfirmPartner: '',
  ChangeProduct: '',
  ConfirmProduct: '',
  submitOrder: '',
  updateOrder: '',
  canNotFindProductForGivenParameters: '',
  orderAddSuccess: '',
  orderAddFailer: '',
  orderUpdateSuccess: '',
  orderUpdateFailer: '',
  orderDeleteSuccess: '',
  orderDeleteFailer: '',
  choosingOptionFromListIsRequires: '',
  choosingAndConfrimPartnerIsRequired: '',
  choosingAndConfirmProductIsRequired: '',
  choosingAndConfirmMaterialIsRequired: '',
  changeDrawingParameters: '',
  yourCommentToOrder: '',
  businessPartnerName: 'Nazwa Parnera Handlowego',
  businessPartners: 'Partne Handlowy',
  productType: 'Typ Produktu',
  productTop: 'Wykończenie Góry',
  productBottom: 'Wykończenie Dna',
  pressButtonToChooseProductByDrawing: 'naciśnij przycisk aby wybrać product na podstawie rysunku',
  chooseProductByDrawingButtonDescription: 'Wybierz Product klikając na rysunek',
  chooseProductByParameters: ' Wybierz produkt określając parametry produktu',
  productMaterial: 'Materiał Produktu',
  addNewProductBottom: '',
  addNewProductTop: '',
  addNewProductType: '',
  addNewProduct: '',
  updateProductBottom: '',
  updateProductTop: '',
  updateProductType: '',
  updateProduct: '',
  productBottomCode: '',
  productBottomName: '',


};

export const drawingTableFormNames = {
  workingTemperature: '',
  antielectrostatic: '',
  workingSide: '',
  workingSideExternal: '',
  workingSideInternal: '',
  material: '',
};
export const dimensionNames = {
  dimensionCode: 'Kod wymiaru',
  dimensionRole: 'Rola wymiaru',
  dimensionRoleFirstIndex: 'Pierwszy wymiar indeksu',
  dimensionRoleSecondIndex: 'Drugi wymiar indeksu',
  dimensionRoleNoIndex: 'Wymiar nie wchcodzący do indeksu',
  dimensionName:'',
  selectDimensionRole: ''

}
export const languageNames = {
  languageCode: 'Kod Języka',
  languageName: 'Nazwa Języka',
  flag: 'Flaga',

}

export const materialNamesInSelectedLanguage = {
  materialCode: '',
  materialName: '',
  addNewMaterial: '',
  updateMaterial: '',
  quantity: '',
  search: '',
  materialCodeMustContain6CHaracters: ''
};
